/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:02:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.telosys.gwtp.base.shared.dto;

import java.io.Serializable;

import javax.validation.constraints.NotNull;

/**
 * Java bean for entity "BOOK_ORDER_ITEM" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookOrderItemDto implements Serializable {
	private static final long serialVersionUID = 1L;

	@NotNull
	private Integer bookOrderId; // Integer // Id or Primary Key
	@NotNull
	private Integer bookId; // Integer // Id or Primary Key

	@NotNull
	private Integer quantity; // Integer
	@NotNull
	private Double price; // BigDecimal

	/**
	 * Default constructor
	 */
	public BookOrderItemDto() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY
	// ----------------------------------------------------------------------
	/**
	 * Set the "bookOrderId" field value This field is mapped on the database
	 * column "BOOK_ORDER_ID" ( type "INTEGER", NotNull : true )
	 * 
	 * @param bookOrderId
	 */
	public void setBookOrderId(Integer bookOrderId) {
		this.bookOrderId = bookOrderId;
	}

	/**
	 * Get the "bookOrderId" field value This field is mapped on the database
	 * column "BOOK_ORDER_ID" ( type "INTEGER", NotNull : true )
	 * 
	 * @return the field value
	 */
	public Integer getBookOrderId() {
		return this.bookOrderId;
	}

	/**
	 * Set the "bookId" field value This field is mapped on the database column
	 * "BOOK_ID" ( type "INTEGER", NotNull : true )
	 * 
	 * @param bookId
	 */
	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	/**
	 * Get the "bookId" field value This field is mapped on the database column
	 * "BOOK_ID" ( type "INTEGER", NotNull : true )
	 * 
	 * @return the field value
	 */
	public Integer getBookId() {
		return this.bookId;
	}

	// ----------------------------------------------------------------------
	// GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
	// ----------------------------------------------------------------------

	/**
	 * Set the "quantity" field value This field is mapped on the database
	 * column "QUANTITY" ( type "INTEGER", NotNull : true )
	 * 
	 * @param quantity
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * Get the "quantity" field value This field is mapped on the database
	 * column "QUANTITY" ( type "INTEGER", NotNull : true )
	 * 
	 * @return the field value
	 */
	public Integer getQuantity() {
		return this.quantity;
	}

	/**
	 * Set the "price" field value This field is mapped on the database column
	 * "PRICE" ( type "DECIMAL", NotNull : true )
	 * 
	 * @param price
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * Get the "price" field value This field is mapped on the database column
	 * "PRICE" ( type "DECIMAL", NotNull : true )
	 * 
	 * @return the field value
	 */
	public Double getPrice() {
		return this.price;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(bookOrderId);
		sb.append("|");
		sb.append(bookId);
		sb.append("|");
		sb.append(quantity);
		sb.append("|");
		sb.append(price);
		return sb.toString();
	}

}
